# clients.yaml
clients:
  - id: C1
    name: DailyShop
    inbound:
      pattern: interval
      base_interval_min: 720   # каждые 12 часов
      jitter_min: -60
      jitter_max: 60
      batch_mean_lines: 100   # сколько разных SKU в поставке (Пуассон)
      sku_qty_mean: 50        # среднее количество каждой позиции
    outbound:
      pattern: interval
      base_interval_min: 1440   # раз в сутки
      jitter_min: -120
      jitter_max: 120
      lines_mean: 80            # среднее линий (Пуассон)
    sku_mix:
      - {sku: S_PEPSI_05, weight: 5}
      - {sku: S_COLA_15,  weight: 3}
      - {sku: S_SNACK_X,  weight: 2}

  - id: C2
    name: TwiceWeek
    inbound:
      pattern: interval
      base_interval_min: 720   # каждые 12 часов
      jitter_min: -60
      jitter_max: 60
      batch_mean_lines: 100   # сколько разных SKU в поставке (Пуассон)
      sku_qty_mean: 50        # среднее количество каждой позиции
    outbound:
      pattern: weekly
      days: [1,4]               # 0=Monday (задание соглашения)
      time_minute_of_day: 600   # 10:00
      jitter_min: -30
      jitter_max: 30
      lines_mean: 120
    sku_mix:
      - {sku: S_PEPSI_05, weight: 10}
      - {sku: S_COLA_15,  weight: 5}
      - {sku: S_SNACK_X,  weight: 1}
