# clients.yaml
clients:
  - id: C1
    name: DailyShop

    inbound:
      pattern: interval
      # Поставки каждые 1 минуту
      base_interval_min: 1
      jitter_min:         0
      jitter_max:         0
      # Каждая поставка ≈50 линий → 5 рабочих не простаивают
      batch_mean_lines:   50
      sku_qty_mean:       1

    outbound:
      pattern: interval
      base_interval_min: 0.6667   # 40 сек
      jitter_min: 0
      jitter_max: 0
      batch_mean_lines: 50         # вместо lines_mean
      lines_mean: 20
      sku_qty_mean: 1              # добавляем, иначе 0

    sku_mix:
      - {sku: S_PEPSI_05, weight: 5}
      - {sku: S_COLA_15,  weight: 3}
      - {sku: S_SNACK_X,  weight: 2}
