# sim_params.yaml
# ================== SIMULATION CONFIG ==================
# Все времена в секундах сим‑времени.

files:
  layout: config/layout.yaml
  skus:   config/skus.yaml
  clients: config/clients.yaml

time:
  # Длительность симуляции: 1 час
  shift_seconds:       3600
  # Шаг тика в секундах
  base_tick_seconds:   1

# Генерация заказных линий (order_generation.py)
orders:
  lines_lambda_per_min: 45     # ≈45 линий в минуту
  line_pick_time_base: 12      # базовое время на линию
  zone_multipliers:
    A: 1.0
    B: 1.1
  deadline_min: 60

dispatcher:
  max_assign_per_step:          8
  look_ahead_lines_per_worker:  1

workers:
  pickers:            5         # 5 сборщиков
  speed_cells_per_sec: 1.0

metrics:
  sample_interval_seconds: 60

inventory:
  initial_stock:      0
  allow_negative:     false

dump:
  snap_every_sec:     1
  keep_snapshots_days: 30

# Оптимайзер (не трогаем)
optimizer:
  period_min:         123123

# --- Вот добавленный блок waves, без него код падает на KeyError ---
waves:
  # Время таймаута при сборке волны (сек)
  build_timeout_seconds: 300
